experiment_name: Pig_Posture_Prediction
run_name: run04

train_ann: data/split/train.csv
train_dir: data/train_images/

test_ann: data/test.csv
test_dir: data/test_images/

val_ann: data/split/val.csv
val_dir: data/train_images/

output_dir: "output/"

model_name: convnext_small

num_classes: 5
epoch: 10
num_workers: 4
batch_size: 4
shuffle: False
drop_last: False
pin_memory: False

resume: output/run12/best_epoch.pth
resume_optimizer: None
resume_itr: 0
task: inference


# scheduler:
#   type: "ReduceLROnPlateau"
#   params:
#     factor: 0.1
#     patience: 4

# scheduler:
#   type: "StepLR"
#   params:
#     step_size: 2
#     gamma: 0.1

scheduler:
  type: CosineAnnealingLR
  params:
    T_max: 20

# lr orig is 0.0001, *0.1 after 16 epoch
# optimizer:
#   type: "SGD"
#   params:
#     lr: 0.0001
#     weight_decay: 0.0001

optimizer:
  type: AdamW
  params:
    #lr: 1e-5
    lr: 0.00001
    #weight_decay: 0.05
    weight_decay: 0.0001
    betas: [0.9, 0.999]


# augmentation:
#   color_jitter:
#     brightness: 0.2
#     contrast: 0.2
#     saturation: 0.2
#     hue: 0.1